version: "3.7"

services:
  web:
    container_name: web_container
    build:
      context: ./web/
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    container_name: nginx_container
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web

  db:
    image: postgres:11
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
